//! GENERATED by tools/gen_target_registry.py. DO NOT EDIT.

pub const APPLE8_PROFILE_NAME: &str = "macos-arm64-metal-apple8-v1";
pub const APPLE8_PROFILE_ID: u32 = 1;
pub const APPLE8_EXECUTION_LAYOUT_ABI: u32 = 1;
pub const APPLE8_KERNEL_ABI: u32 = 1;
pub const APPLE8_TARGET_CLASS: u32 = 0x01000001;
pub const APPLE8_MXFP4_TILE_LAYOUT: u16 = 0x0103;
pub const APPLE8_MXFP4_TILE_ROWS: u64 = 8;
pub const APPLE8_MXFP4_TILE_COLUMNS: u64 = 32;
pub const APPLE8_MXFP4_TILE_BYTES: u64 = 136;
