#!/usr/bin/env python3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / "tools" / "make_qwen_moe_tiny.py"
TEST = ROOT / "tests" / "test_qwen_prefix_serve.py"


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise SystemExit(f"{label}: expected one match, found {count}")
    return text.replace(old, new, 1)


g = GEN.read_text()
g = replace_once(
    g,
    '            "special": True,\n',
    '            # Added tokens must stay atomic for the tiny tokenizer, but only\n'
    '            # EOS is a generation stop. Marking every <tNNN> special makes\n'
    '            # sample.h arm the entire vocabulary as hard stops in SERVE=1.\n'
    '            "special": token == EOS,\n',
    "tiny tokenizer special flag",
)
GEN.write_text(g)

t = TEST.read_text()
t = replace_once(
    t,
    '''    short = list(reference["cases"]["short"]["prompt_ids"])\n'''
    '''    mixed = list(reference["cases"]["mixed"]["prompt_ids"])\n''',
    '''    short_case = reference["cases"]["short"]\n'''
    '''    mixed_case = reference["cases"]["mixed"]\n'''
    '''    short = list(short_case["prompt_ids"])\n'''
    '''    mixed = list(mixed_case["prompt_ids"])\n''',
    "reference cases",
)
t = replace_once(
    t,
    '''    short_prompt = token_prompt(short)\n'''
    '''    mixed_prompt = token_prompt(mixed)\n''',
    '''    short_prompt = token_prompt(short)\n'''
    '''    mixed_prompt = token_prompt(mixed)\n'''
    '''    expected_short = token_prompt(list(short_case["greedy_new_ids"])[:4])\n'''
    '''    expected_mixed = token_prompt(list(mixed_case["greedy_new_ids"])[:4])\n'''
    '''    if not expected_short or not expected_mixed:\n'''
    '''        raise AssertionError("tiny oracle must contain non-empty generated tokens")\n''',
    "expected generated bytes",
)
t = replace_once(
    t,
    '''    if first != repeated or repeated != cold_short:\n'''
    '''        raise AssertionError(\n'''
    '''            "repeating an identical prompt changed output; strict-prefix miss "\n'''
    '''            "did not behave like a cold full prefill"\n'''
    '''        )\n''',
    '''    if first != expected_short or repeated != expected_short or cold_short != expected_short:\n'''
    '''        raise AssertionError(\n'''
    '''            "short serve output did not match the Transformers-generated token oracle; "\n'''
    '''            f"expected={expected_short!r} first={first!r} repeated={repeated!r} cold={cold_short!r}"\n'''
    '''        )\n''',
    "short non-vacuous oracle",
)
t = replace_once(
    t,
    '''    if reused != cold_mixed:\n'''
    '''        raise AssertionError(\n'''
    '''            "restoring the hybrid prompt state changed generation:\\n"\n'''
    '''            f"  warm={reused!r}\\n  cold={cold_mixed!r}"\n'''
    '''        )\n''',
    '''    if reused != expected_mixed or cold_mixed != expected_mixed:\n'''
    '''        raise AssertionError(\n'''
    '''            "restoring the hybrid prompt state changed generation or diverged from "\n'''
    '''            "the Transformers-generated token oracle:\\n"\n'''
    '''            f"  expected={expected_mixed!r}\\n  warm={reused!r}\\n  cold={cold_mixed!r}"\n'''
    '''        )\n''',
    "mixed non-vacuous oracle",
)
TEST.write_text(t)
print("qwen tiny serve oracle now requires real generated DATA tokens")
