CC ?= cc
CFLAGS ?= -O2 -std=c11 -Wall -Wextra -Werror
EXE :=
ifeq ($(OS),Windows_NT)
EXE := .exe
endif

.PHONY: check clean

check: test_record_io$(EXE) test_expert_representation$(EXE) test_expert_residency$(EXE) test_expert_multivariant$(EXE) test_expert_transform$(EXE) test_expert_dispatch$(EXE) test_expert_dispatch_output$(EXE) test_expert_derived_cache$(EXE) test_expert_activation$(EXE) test_expert_residency_policy$(EXE) test_expert_resource_bridge$(EXE) test_resource_planner$(EXE) test_speculative_cache$(EXE) test_speculative_cache_disk$(EXE)
	./test_record_io$(EXE)
	./test_expert_representation$(EXE)
	./test_expert_residency$(EXE)
	./test_expert_multivariant$(EXE)
	./test_expert_transform$(EXE)
	./test_expert_dispatch$(EXE)
	./test_expert_dispatch_output$(EXE)
	./test_expert_derived_cache$(EXE)
	./test_expert_activation$(EXE)
	./test_expert_residency_policy$(EXE)
	./test_expert_resource_bridge$(EXE)
	./test_resource_planner$(EXE)
	./test_speculative_cache$(EXE)
	./test_speculative_cache_disk$(EXE)

test_record_io$(EXE): tests/test_record_io.c record_io.h
	$(CC) $(CFLAGS) tests/test_record_io.c -o $@

test_expert_representation$(EXE): tests/test_expert_representation.c expert_representation.h coli_format.h
	$(CC) $(CFLAGS) tests/test_expert_representation.c -o $@

test_expert_residency$(EXE): tests/test_expert_residency.c expert_residency.h expert_representation.h expert_store.h coli_format.h
	$(CC) $(CFLAGS) tests/test_expert_residency.c -o $@

test_expert_multivariant$(EXE): tests/test_expert_multivariant.c expert_residency.h expert_representation.h expert_store.h coli_format.h
	$(CC) $(CFLAGS) tests/test_expert_multivariant.c -o $@

test_expert_transform$(EXE): tests/test_expert_transform.c expert_transform.c expert_transform.h expert_residency.h expert_representation.h expert_store.h coli_format.h
	$(CC) $(CFLAGS) tests/test_expert_transform.c expert_transform.c -o $@

test_expert_dispatch$(EXE): tests/test_expert_dispatch.c expert_dispatch.h expert_transform.c expert_transform.h expert_residency.h expert_residency_policy.h expert_activation.h resource_planner.h expert_representation.h expert_store.h coli_format.h
	$(CC) $(CFLAGS) tests/test_expert_dispatch.c expert_transform.c -o $@

test_expert_dispatch_output$(EXE): tests/test_expert_dispatch_output.c expert_dispatch.h expert_transform.c expert_transform.h expert_residency.h expert_residency_policy.h expert_activation.h resource_planner.h expert_representation.h expert_store.h coli_format.h
	$(CC) $(CFLAGS) tests/test_expert_dispatch_output.c expert_transform.c -o $@

test_expert_derived_cache$(EXE): tests/test_expert_derived_cache.c expert_derived_cache.c expert_derived_cache.h cache_io.h expert_transform.c expert_transform.h expert_residency.h expert_representation.h expert_store.h coli_format.h
	$(CC) $(CFLAGS) tests/test_expert_derived_cache.c expert_derived_cache.c expert_transform.c -o $@

test_expert_activation$(EXE): tests/test_expert_activation.c expert_activation.h expert_store.h
	$(CC) $(CFLAGS) tests/test_expert_activation.c -o $@

test_expert_residency_policy$(EXE): tests/test_expert_residency_policy.c expert_residency_policy.h expert_activation.h expert_store.h resource_planner.h
	$(CC) $(CFLAGS) tests/test_expert_residency_policy.c -o $@

test_expert_resource_bridge$(EXE): tests/test_expert_resource_bridge.c expert_residency_policy.h expert_activation.h expert_store.h resource_planner.h
	$(CC) $(CFLAGS) tests/test_expert_resource_bridge.c -o $@

test_resource_planner$(EXE): tests/test_resource_planner.c resource_planner.h
	$(CC) $(CFLAGS) tests/test_resource_planner.c -o $@

test_speculative_cache$(EXE): tests/test_speculative_cache.c speculative_cache.h
	$(CC) $(CFLAGS) tests/test_speculative_cache.c -o $@

test_speculative_cache_disk$(EXE): tests/test_speculative_cache_disk.c speculative_cache_disk.h speculative_cache.h
	$(CC) $(CFLAGS) tests/test_speculative_cache_disk.c -o $@

clean:
	rm -f test_record_io test_record_io.exe \
		test_expert_representation test_expert_representation.exe \
		test_expert_residency test_expert_residency.exe \
		test_expert_multivariant test_expert_multivariant.exe \
		test_expert_transform test_expert_transform.exe \
		test_expert_dispatch test_expert_dispatch.exe \
		test_expert_dispatch_output test_expert_dispatch_output.exe \
		test_expert_derived_cache test_expert_derived_cache.exe \
		test_expert_activation test_expert_activation.exe \
		test_expert_residency_policy test_expert_residency_policy.exe \
		test_expert_resource_bridge test_expert_resource_bridge.exe \
		test_resource_planner test_resource_planner.exe \
		test_speculative_cache test_speculative_cache.exe \
		test_speculative_cache_disk test_speculative_cache_disk.exe
