#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "abi" / "coli-target-registry.json"
C_OUT = ROOT / "c" / "generated" / "coli_target_registry.h"
RUST_OUT = ROOT / "colic" / "src" / "target_registry.rs"


def load():
    data = json.loads(SOURCE.read_text())
    if data.get("schema") != 1:
        raise SystemExit("unsupported target registry schema")
    profile_name = "macos-arm64-metal-apple8-v1"
    profile = data["profiles"][profile_name]
    layout = profile["layouts"]["mxfp4-tile8x32-v1"]
    return profile_name, profile, layout


def c_text(profile_name, profile, layout):
    return f'''/* GENERATED by tools/gen_target_registry.py. DO NOT EDIT. */
#ifndef COLI_GENERATED_TARGET_REGISTRY_H
#define COLI_GENERATED_TARGET_REGISTRY_H

#define COLI_TARGET_PROFILE_MACOS_ARM64_METAL_APPLE8_V1 "{profile_name}"
#define COLI_TARGET_PROFILE_ID_MACOS_ARM64_METAL_APPLE8_V1 {profile["profile_id"]}u
#define COLI_EXECUTION_LAYOUT_ABI_APPLE8_V1 {profile["execution_layout_abi"]}u
#define COLI_KERNEL_ABI_APPLE8_MXFP4_TILE_V1 {profile["kernel_abi"]}u
#define COLI_TARGET_CLASS_APPLE8_METAL_V1 0x{profile["target_class"]:08x}u
#define COLI_LAYOUT_APPLE_MXFP4_TILE8X32_V1 0x{layout["id"]:04x}u
#define COLI_APPLE8_MXFP4_TILE_ROWS {layout["tile_rows"]}u
#define COLI_APPLE8_MXFP4_TILE_COLUMNS {layout["tile_columns"]}u
#define COLI_APPLE8_MXFP4_TILE_BYTES {layout["tile_bytes"]}u

#endif
'''


def rust_text(profile_name, profile, layout):
    return f'''//! GENERATED by tools/gen_target_registry.py. DO NOT EDIT.

pub const APPLE8_PROFILE_NAME: &str = "{profile_name}";
pub const APPLE8_PROFILE_ID: u32 = {profile["profile_id"]};
pub const APPLE8_EXECUTION_LAYOUT_ABI: u32 = {profile["execution_layout_abi"]};
pub const APPLE8_KERNEL_ABI: u32 = {profile["kernel_abi"]};
pub const APPLE8_TARGET_CLASS: u32 = 0x{profile["target_class"]:08x};
pub const APPLE8_MXFP4_TILE_LAYOUT: u16 = 0x{layout["id"]:04x};
pub const APPLE8_MXFP4_TILE_ROWS: u64 = {layout["tile_rows"]};
pub const APPLE8_MXFP4_TILE_COLUMNS: u64 = {layout["tile_columns"]};
pub const APPLE8_MXFP4_TILE_BYTES: u64 = {layout["tile_bytes"]};
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    profile_name, profile, layout = load()
    outputs = [(C_OUT, c_text(profile_name, profile, layout)),
               (RUST_OUT, rust_text(profile_name, profile, layout))]
    if args.check:
        bad = [str(path.relative_to(ROOT)) for path, text in outputs
               if not path.exists() or path.read_text() != text]
        if bad:
            raise SystemExit("generated target registry is stale: " + ", ".join(bad))
        return
    for path, text in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)

if __name__ == "__main__":
    main()
