#!/usr/bin/env python3
"""Generate dependency-free Rust/C constants from spec/coli-target-profiles-v1.json."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "spec/coli-target-profiles-v1.json"
RUST = ROOT / "colic/src/target/profiles_generated.rs"
C_HEADER = ROOT / "c/coli_target_profiles_generated.h"


def macro(name: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in name).upper()


def rust_output(spec: dict) -> str:
    out = [
        "// @generated by tools/generate_target_profiles.py; do not edit.\n",
        f'pub const SEMANTIC_ABI: &str = {spec["semantic_abi"]!r};\n'.replace("'", '"'),
    ]
    for name, value in spec["layouts"].items():
        out.append(f"pub const LAYOUT_{macro(name)}: u16 = 0x{value:04x};\n")
    out.append("\n")
    names = []
    for p in spec["profiles"]:
        ident = macro(p["name"])
        names.append(ident)
        fields = [
            ("id", f'{p["id"]}'),
            ("name", f'"{p["name"]}"'),
            ("semantic_abi", "SEMANTIC_ABI"),
            ("target_os", f'{p["target_os"]}'),
            ("target_arch", f'{p["target_arch"]}'),
            ("backend", f'{p["backend"]}'),
            ("gpu_kind", f'{p["gpu_kind"]}'),
            ("cpu_feature_mask", f'{p["cpu_feature_mask"]}'),
            ("gpu_family_min", f'{p["gpu_family_min"]}'),
            ("gpu_family_max", f'{p["gpu_family_max"]}'),
            ("gpu_capability_min", f'{p["gpu_capability_min"]}'),
            ("gpu_capability_max", f'{p["gpu_capability_max"]}'),
            ("target_profile_abi", f'{p["target_profile_abi"]}'),
            ("execution_layout_abi", f'{p["execution_layout_abi"]}'),
            ("kernel_abi_min", f'{p["kernel_abi_min"]}'),
            ("kernel_abi_max", f'{p["kernel_abi_max"]}'),
            ("record_alignment", f'{p["record_alignment"]}'),
            ("io_granularity", f'{p["io_granularity"]}'),
            ("resident_alignment", f'{p["resident_alignment"]}'),
            ("required_runtime_features", f'{p["required_runtime_features"]}'),
            ("target_flags", f'{p["target_flags"]}'),
            ("quant_profile", f'"{p["quant_profile"]}"'),
            ("storage_profile", f'"{p["storage_profile"]}"'),
            ("optimization_profile", f'"{p["optimization_profile"]}"'),
            ("kernel_profile", f'"{p["kernel_profile"]}"'),
            ("target_triple", f'"{p["target_triple"]}"'),
            ("lowering_available", str(bool(p["lowering_available"])).lower()),
        ]
        out.append(f"pub const {ident}: TargetProfile = TargetProfile {{\n")
        out.extend(f"    {key}: {value},\n" for key, value in fields)
        out.append("};\n\n")
    out.append("pub const PROFILES: &[TargetProfile] = &[\n")
    out.extend(f"    {name},\n" for name in names)
    out.append("];\n")
    return "".join(out)


def c_output(spec: dict) -> str:
    out = [
        "/* @generated by tools/generate_target_profiles.py; do not edit. */\n",
        "#ifndef COLI_TARGET_PROFILES_GENERATED_H\n#define COLI_TARGET_PROFILES_GENERATED_H\n\n",
        f'#define COLI_TARGET_SEMANTIC_ABI "{spec["semantic_abi"]}"\n',
    ]
    for name, value in spec["layouts"].items():
        out.append(f"#define COLI_CSF_LAYOUT_{macro(name)} 0x{value:04x}u\n")
    out.append("\n")
    for p in spec["profiles"]:
        stem = f'COLI_TARGET_{macro(p["name"])}'
        for key in (
            "id", "target_os", "target_arch", "backend", "gpu_kind",
            "cpu_feature_mask", "gpu_family_min", "gpu_family_max",
            "gpu_capability_min", "gpu_capability_max", "target_profile_abi",
            "execution_layout_abi", "kernel_abi_min", "kernel_abi_max",
            "record_alignment", "io_granularity", "resident_alignment",
            "required_runtime_features", "target_flags",
        ):
            suffix = key.upper()
            out.append(f"#define {stem}_{suffix} {p[key]}u\n")
        for key in ("name", "quant_profile", "storage_profile", "optimization_profile", "kernel_profile", "target_triple"):
            out.append(f'#define {stem}_{key.upper()} "{p[key]}"\n')
        out.append(f"#define {stem}_LOWERING_AVAILABLE {1 if p['lowering_available'] else 0}u\n\n")
    out.append("#endif /* COLI_TARGET_PROFILES_GENERATED_H */\n")
    return "".join(out)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    spec = json.loads(SPEC.read_text())
    expected = {RUST: rust_output(spec), C_HEADER: c_output(spec)}
    if args.check:
        bad = [str(path.relative_to(ROOT)) for path, text in expected.items() if not path.exists() or path.read_text() != text]
        if bad:
            print("generated target profile files are stale: " + ", ".join(bad))
            return 1
        return 0
    for path, text in expected.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
